### ISSUE TITLE
[1.19.2 forge] Mod load error

### ISSUE THREAD

**Issue by n0proxy** [Insane96/PathToDirt#4]
Mod loading error on 1.19.2, using either mod version 1.5.0 or 1.5.1.

[crash-2022-11-04_15.25.25-fml.txt](https://github.com/Insane96/PathToDirt/files/9942337/crash-2022-11-04_15.25.25-fml.txt)

**Comment by Insane96** [comment]
1.5.2 as soon as it's approved by CurseForge
