### ISSUE TITLE
[1.20.1] Crash with newest InsaneLib

### ISSUE THREAD

**Issue by lays24mc** [Insane96/PathToDirt#5]
Hi,

with the new InsaneLib version, unfortunately the mod "Path to Dirth" doesn't work anymore. The client stops with the error "java.lang.reflect.InvocationTargetException".

The log: https://pastebin.com/0Yfv28fa

Insanelib 1.11.1-mc1.20.1
PathToDirt 1.7.0
Forge 47.1.3

**Comment by Insane96** [comment]
Fixed in 1.7.1
