### ISSUE TITLE
1.7.5 - Cannot Return Path to Dirt or Edit Config In-game

### ISSUE THREAD

**Issue by burghenby** [Insane96/PathToDirt#7]
I updated to 1.7.5 today and noticed that I could no longer right-click to return paths to dirt. When I went to review my config, in case I needed to remove something for a mod that was no longer installed, I observed that I could no longer edit the config in-game either where previously I had via Forge Config Screens and Catalogue.

I closed my game, manually edited my config, and reopened my game, but still could not right-click to return path to dirt. I then returned the mod to 1.7.4 and can once again right-click to return path to dirt.

**Forge**: 47.3.0
**InsaneLib**: 1.13.5
**Minecraft**: 1.20.1

**Comment by Insane96** [comment]
Update InsaneLib

**Comment by burghenby** [comment]
Ah, I see... While Path-to-Dirt updated, InsaneLib did not. I use Prismlauncher and Path-to-Dirt was connected to Curseforge but InsaneLib was connected to Modrinth, and both mods have not been updated on Modrinth in a hot minute. I've adjusted the update connection for Prismlauncher... but perhaps you could get the updates on Modrinth matched to Curseforge? Either that, or just take it down from Modrinth altogether. 🤷
